#!/usr/bin/env sh
set -eu

mode=read
if [ "${1-}" = "manifest" ]; then
    exec /usr/bin/docker "$@"
fi

case "${1-}" in
    start|stop|restart|compose)
        mode=write
        ;;
    container|network|builder)
        if [ "${2-}" = "prune" ]; then mode=write; fi
        ;;
    image)
        case "${2-}" in
            rm|prune) mode=write ;;
        esac
        ;;
esac

exec /usr/bin/pkexec /usr/lib/docker-tray/docker_tray_privileged.py \
    "$mode" --cwd "$PWD" -- "$@"
